version: '3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      #- MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    command: --max_allowed_packet=128M
    restart: unless-stopped
    ports: 
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql