version: '3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      #- MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    command: --max_allowed_packet=128M
    restart: unless-stopped
    ports: 
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./mysql_data_prd:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  server:
    image: docker.io/yumol/hsl-city-bike-backend:v1
    container_name: hsl-city-bike-backend
    depends_on: 
      - mysql
    ports:
      - "3001:3001"
    volumes: 
      - ./logs:/usr/src/app/logs
  
  app:
    image: docker.io/yumol/hsl-city-bike-frontend:v1
    container_name: hsl-city-bike-frontend
    ports:
      - "3000:3000"
    
  